apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicd
spec:
  selector:
    matchLabels:
      app: cicd
  template:
    metadata:
      labels:
        app: cicd
    spec:
      containers:
      - name: cicd
        image: ubuntu:docker_tag
        command: ["/bin/sh"]
        args: ["-c","sh /usr/local/tomcat/bin/startup.sh;while true; do echo hello; sleep 10;done"]
        ports:
            - name: http
              containerPort: 8080
  replicas: 2
---
apiVersion: v1
kind: Service
metadata:
  name: app-service
  labels:
    app: cicd
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 31884
    protocol: TCP
    name: http
  selector:
    app: cicd
